"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Field from "../../components/Field";
import { api,save } from "../../lib/api";

export default function Register(){
 const r=useRouter();const[f,setF]=useState({name:"",email:"",password:""});const[err,setErr]=useState("");const[busy,setBusy]=useState(false);
 async function submit(x:FormEvent){x.preventDefault();setErr("");if(f.password.length<8)return setErr("Password must be at least 8 characters");setBusy(true);try{const d=await api<{access_token:string}>("/auth/register",{method:"POST",body:JSON.stringify(f)});save(d.access_token);r.push("/dashboard")}catch(x){setErr(x instanceof Error?x.message:"Registration failed")}finally{setBusy(false)}}
 return <main className="min-h-screen grid lg:grid-cols-2 bg-white"><div className="hidden lg:flex bg-[#0b1020] text-white p-14 flex-col justify-between"><div className="text-2xl font-black">Social<span className="text-[#8c84ff]">Flow</span></div><div><p className="text-5xl font-black leading-tight">Build a publishing system, not another to-do list.</p><p className="mt-5 text-slate-300 text-lg">A focused workspace for creators, teams and growing brands.</p></div><p className="text-slate-500 text-sm">Secure JWT authentication • PostgreSQL</p></div><div className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md space-y-5"><div className="lg:hidden text-2xl font-black mb-10">Social<span className="text-[#635bff]">Flow</span></div><div><h1 className="text-3xl font-black">Create your workspace</h1><p className="mt-2 muted">Start organizing your social content.</p></div>{err&&<p className="rounded-xl bg-red-50 border border-red-100 p-3 text-sm text-red-700">{err}</p>}<Field label="Full name" value={f.name} onChange={x=>setF({...f,name:x.target.value})} required/><Field label="Email" type="email" value={f.email} onChange={x=>setF({...f,email:x.target.value})} required/><Field label="Password" type="password" minLength={8} value={f.password} onChange={x=>setF({...f,password:x.target.value})} required/><button disabled={busy} className="btn btn-primary w-full py-3 disabled:opacity-60">{busy?"Creating…":"Create account"}</button><p className="text-center text-sm muted">Already have an account? <Link className="text-[#635bff] font-semibold" href="/login">Sign in</Link></p></form></div></main>
}
