"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { api,logout } from "../../lib/api";

type User={name:string,email:string};
type Account={id:number,platform:string,username:string,connected:boolean};
type Post={id:number,content:string,platform:string,status:string,scheduled_at:string|null,published_at:string|null,created_at:string|null};
type Stats={total_posts:number,drafts:number,scheduled:number,published:number,connected_accounts:number,upcoming:Post[]};
const platforms=["Instagram","Facebook","LinkedIn","X","TikTok"];

const icon=(p:string)=>({Instagram:"◎",Facebook:"f",LinkedIn:"in",X:"𝕏",TikTok:"♪"}[p]||"•");

function localValue(iso:string|null){if(!iso)return "";const d=new Date(iso);const pad=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}

export default function Dashboard(){
 const r=useRouter();
 const [u,setU]=useState<User|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[posts,setPosts]=useState<Post[]>([]),[stats,setStats]=useState<Stats|null>(null);
 const [content,setContent]=useState(""),[when,setWhen]=useState(""),[platform,setPlatform]=useState("Instagram"),[accountPlatform,setAccountPlatform]=useState("Instagram"),[username,setUsername]=useState("");
 const [query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[err,setErr]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<Post|null>(null),[editContent,setEditContent]=useState(""),[editWhen,setEditWhen]=useState(""),[editPlatform,setEditPlatform]=useState("Instagram");

 async function load(){try{const [x,a,p,s]=await Promise.all([api<User>("/users/me"),api<Account[]>("/social-accounts"),api<Post[]>("/posts"),api<Stats>("/analytics")]);setU(x);setAccounts(a);setPosts(p);setStats(s)}catch{logout();r.push("/login")}}
 useEffect(()=>{load()},[]);
 function flash(message:string){setNotice(message);setTimeout(()=>setNotice(""),2500)}
 async function create(e:FormEvent){e.preventDefault();setErr("");setBusy(true);try{await api("/posts",{method:"POST",body:JSON.stringify({content,platform,scheduled_at:when?new Date(when).toISOString():null})});setContent("");setWhen("");flash(when?"Post scheduled successfully":"Draft saved");await load()}catch(x){setErr(x instanceof Error?x.message:"Could not save post")}finally{setBusy(false)}}
 async function addAccount(e:FormEvent){e.preventDefault();setErr("");try{await api("/social-accounts",{method:"POST",body:JSON.stringify({platform:accountPlatform,username})});setUsername("");flash("Account connected");await load()}catch(x){setErr(x instanceof Error?x.message:"Could not connect account")}}
 async function removeAccount(id:number){if(!confirm("Disconnect this account?"))return;await api(`/social-accounts/${id}`,{method:"DELETE"});flash("Account disconnected");load()}
 async function removePost(id:number){if(!confirm("Delete this post permanently?"))return;await api(`/posts/${id}`,{method:"DELETE"});flash("Post deleted");load()}
 async function publish(id:number){await api(`/posts/${id}/publish`,{method:"POST"});flash("Post marked as published");load()}
 async function duplicate(id:number){await api(`/posts/${id}/duplicate`,{method:"POST"});flash("Draft duplicated");load()}
 function openEdit(p:Post){setEditing(p);setEditContent(p.content);setEditPlatform(p.platform);setEditWhen(localValue(p.scheduled_at))}
 async function saveEdit(e:FormEvent){e.preventDefault();if(!editing)return;await api(`/posts/${editing.id}`,{method:"PUT",body:JSON.stringify({content:editContent,platform:editPlatform,scheduled_at:editWhen?new Date(editWhen).toISOString():null})});setEditing(null);flash("Post updated");load()}

 const visible=useMemo(()=>posts.filter(p=>(filter==="all"||p.status===filter)&&(`${p.content} ${p.platform}`.toLowerCase().includes(query.toLowerCase()))),[posts,filter,query]);
 const upcoming=(stats?.upcoming||[]);
 return <main className="min-h-screen">
  <aside className="fixed inset-y-0 left-0 hidden w-64 bg-[#0b1020] text-white lg:flex flex-col p-5 z-20"><div className="text-2xl font-black px-2">Social<span className="text-[#8c84ff]">Flow</span></div><div className="mt-10 space-y-1"><div className="rounded-xl bg-white/10 px-3 py-2.5 font-semibold">⌂ <span className="ml-2">Overview</span></div><button onClick={()=>document.getElementById("composer")?.scrollIntoView()} className="w-full text-left rounded-xl px-3 py-2.5 text-slate-300 hover:bg-white/5">✦ <span className="ml-2">Create content</span></button><button onClick={()=>document.getElementById("accounts")?.scrollIntoView()} className="w-full text-left rounded-xl px-3 py-2.5 text-slate-300 hover:bg-white/5">◉ <span className="ml-2">Accounts</span></button><button onClick={()=>r.push("/settings")} className="w-full text-left rounded-xl px-3 py-2.5 text-slate-300 hover:bg-white/5">⚙ <span className="ml-2">Settings</span></button></div><div className="mt-auto rounded-2xl bg-white/5 p-4"><p className="text-sm font-semibold truncate">{u?.name}</p><p className="text-xs text-slate-400 truncate">{u?.email}</p><button onClick={()=>{logout();r.push("/login")}} className="mt-4 text-sm text-slate-300 hover:text-white">Sign out →</button></div></aside>
  <div className="lg:pl-64"><header className="sticky top-0 z-10 border-b bg-white/90 backdrop-blur"><div className="flex items-center justify-between px-5 py-4 lg:px-8"><div><p className="text-xs uppercase tracking-widest font-bold text-[#635bff]">Workspace</p><h1 className="text-xl font-black">Command Center</h1></div><div className="flex items-center gap-3"><button onClick={()=>r.push("/settings")} className="btn btn-secondary hidden sm:block">Settings</button><div className="h-10 w-10 rounded-full bg-[#635bff] text-white grid place-items-center font-bold">{u?.name?.slice(0,1).toUpperCase()||"S"}</div></div></div></header>
   <div className="p-5 lg:p-8 max-w-[1500px] mx-auto">
    {notice&&<div className="fixed right-6 top-20 z-50 rounded-xl bg-[#0b1020] text-white px-5 py-3 shadow-xl text-sm">{notice}</div>}
    {err&&<div className="mb-5 rounded-xl border border-red-100 bg-red-50 p-3 text-sm text-red-700">{err}<button className="float-right" onClick={()=>setErr("")}>×</button></div>}
    <section className="mb-7 flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h2 className="text-3xl font-black tracking-tight">Good to see you, {u?.name?.split(" ")[0]||"there"}.</h2><p className="mt-1 muted">Turn ideas into a consistent publishing system.</p></div><button onClick={()=>document.getElementById("composer")?.scrollIntoView({behavior:"smooth"})} className="btn btn-primary">＋ Create post</button></section>
    <section className="grid grid-cols-2 lg:grid-cols-5 gap-4 mb-7">{[["Total posts",stats?.total_posts??0,"All content"],["Drafts",stats?.drafts??0,"Needs work"],["Scheduled",stats?.scheduled??0,"In queue"],["Published",stats?.published??0,"Completed"],["Accounts",stats?.connected_accounts??0,"Connected"]].map(([a,b,c],i)=><div className="card p-5" key={i}><p className="text-sm muted">{a}</p><p className="mt-2 text-3xl font-black">{b}</p><p className="mt-1 text-xs text-slate-400">{c}</p></div>)}</section>
    <div className="grid xl:grid-cols-[1.55fr_.75fr] gap-6">
      <section id="composer" className="card p-6"><div className="flex items-center justify-between"><div><h3 className="text-lg font-black">Content composer</h3><p className="text-sm muted mt-1">Create a draft or schedule it for later.</p></div><span className="rounded-full bg-[#f0efff] text-[#5149dc] px-3 py-1 text-xs font-bold">PRO WORKSPACE</span></div>
       <form onSubmit={create} className="mt-5 space-y-4"><textarea required maxLength={5000} rows={8} value={content} onChange={e=>setContent(e.target.value)} className="input resize-y min-h-[180px]" placeholder="Write something worth publishing…"/><div className="flex justify-between text-xs muted"><span>{content.length}/5000 characters</span><span>{platform} post</span></div><div className="grid md:grid-cols-2 gap-3"><select value={platform} onChange={e=>setPlatform(e.target.value)} className="input">{platforms.map(x=><option key={x}>{x}</option>)}</select><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} className="input" min={localValue(new Date().toISOString())}/></div><div className="flex justify-end gap-3"><button type="button" onClick={()=>{setWhen("");setContent("")}} className="btn btn-secondary">Clear</button><button disabled={busy} className="btn btn-primary disabled:opacity-60">{busy?"Saving…":when?"Schedule post":"Save draft"}</button></div></form>
      </section>
      <section className="card p-6" id="accounts"><div><h3 className="text-lg font-black">Connected accounts</h3><p className="text-sm muted mt-1">Manage publishing destinations.</p></div><form onSubmit={addAccount} className="mt-5 space-y-3"><select value={accountPlatform} onChange={e=>setAccountPlatform(e.target.value)} className="input">{platforms.map(x=><option key={x}>{x}</option>)}</select><div className="flex gap-2"><input required value={username} onChange={e=>setUsername(e.target.value)} placeholder="@handle or profile name" className="input"/><button className="btn btn-primary">Add</button></div></form><div className="mt-5 space-y-2">{accounts.map(a=><div key={a.id} className="flex items-center gap-3 rounded-xl border p-3"><div className="h-9 w-9 rounded-lg bg-slate-100 grid place-items-center font-bold">{icon(a.platform)}</div><div className="min-w-0 flex-1"><p className="text-sm font-bold">{a.platform}</p><p className="text-xs muted truncate">{a.username}</p></div><span className="h-2 w-2 rounded-full bg-emerald-500" title="Connected"/><button onClick={()=>removeAccount(a.id)} className="text-xs text-red-500">Remove</button></div>)}{!accounts.length&&<div className="rounded-xl bg-slate-50 p-4 text-sm muted">No accounts yet. Add one above.</div>}</div></section>
    </div>
    <section className="grid xl:grid-cols-[1.5fr_.8fr] gap-6 mt-6">
      <div className="card overflow-hidden"><div className="p-6 border-b"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h3 className="text-lg font-black">Content library</h3><p className="text-sm muted mt-1">Search, edit, duplicate, publish or delete.</p></div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} className="input md:w-56" placeholder="Search posts…"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="input w-32"><option value="all">All</option><option value="draft">Drafts</option><option value="scheduled">Scheduled</option><option value="published">Published</option></select></div></div></div>
       <div className="divide-y">{visible.map(p=><article key={p.id} className="p-5 hover:bg-slate-50/70 transition"><div className="flex gap-4"><div className="h-10 w-10 shrink-0 rounded-xl bg-[#f0efff] text-[#635bff] grid place-items-center font-bold">{icon(p.platform)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 items-center"><span className="text-sm font-bold">{p.platform}</span><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${p.status==="published"?"bg-emerald-50 text-emerald-700":p.status==="scheduled"?"bg-blue-50 text-blue-700":"bg-amber-50 text-amber-700"}`}>{p.status}</span></div><p className="mt-2 text-sm whitespace-pre-wrap break-words">{p.content}</p><p className="mt-2 text-xs muted">{p.scheduled_at?`Scheduled ${new Date(p.scheduled_at).toLocaleString()}`:p.published_at?`Published ${new Date(p.published_at).toLocaleString()}`:"Draft"}</p></div><div className="flex flex-col gap-2 text-xs"><button onClick={()=>openEdit(p)} className="text-[#635bff] font-semibold">Edit</button><button onClick={()=>duplicate(p.id)} className="muted">Duplicate</button>{p.status!=="published"&&<button onClick={()=>publish(p.id)} className="text-emerald-600 font-semibold">Publish</button>}<button onClick={()=>removePost(p.id)} className="text-red-500">Delete</button></div></div></article>)}{!visible.length&&<div className="p-12 text-center muted">No posts match your filters.</div>}</div>
      </div>
      <aside className="card p-6 h-fit"><div><h3 className="text-lg font-black">Upcoming queue</h3><p className="text-sm muted mt-1">Your next scheduled content.</p></div><div className="mt-5 space-y-3">{upcoming.map(p=><div key={p.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-2"><span className="text-xs font-bold text-[#635bff]">{p.platform}</span><span className="text-xs muted">{p.scheduled_at&&new Date(p.scheduled_at).toLocaleDateString()}</span></div><p className="mt-2 text-sm line-clamp-3">{p.content}</p><p className="mt-2 text-xs muted">{p.scheduled_at&&new Date(p.scheduled_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</p></div>)}{!upcoming.length&&<div className="rounded-xl bg-slate-50 p-5 text-sm muted">Your queue is empty. Schedule a post to see it here.</div>}</div></aside>
    </section>
   </div>
  </div>
  {editing&&<div className="fixed inset-0 z-50 bg-slate-950/50 p-5 grid place-items-center"><form onSubmit={saveEdit} className="card w-full max-w-2xl p-6"><div className="flex justify-between items-center"><div><h3 className="text-xl font-black">Edit post</h3><p className="text-sm muted">Update content, destination or timing.</p></div><button type="button" onClick={()=>setEditing(null)} className="text-2xl muted">×</button></div><textarea required maxLength={5000} rows={8} value={editContent} onChange={e=>setEditContent(e.target.value)} className="input mt-5"/><div className="grid md:grid-cols-2 gap-3 mt-3"><select value={editPlatform} onChange={e=>setEditPlatform(e.target.value)} className="input">{platforms.map(x=><option key={x}>{x}</option>)}</select><input type="datetime-local" value={editWhen} onChange={e=>setEditWhen(e.target.value)} className="input"/></div><div className="flex justify-end gap-3 mt-5"><button type="button" onClick={()=>setEditing(null)} className="btn btn-secondary">Cancel</button><button className="btn btn-primary">Save changes</button></div></form></div>}
 </main>
}
